stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        cd web
        pwd
        echo "Building PAP $PACKAGE_VERSION"
        npm install -g react react-dom
        npm install
        npm run build
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
      - pull_request
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pap:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deploy.yaml
timeout: 60
notification:
  recipients:
  - recipient: '#infra'
    notifier: c-56qv2:n-tvgx2
  condition:
  - Success
  - Failed
